package org.usfirst.frc1318.shared.constants;

import edu.wpi.first.wpilibj.SensorBase;

public interface TBPortRef {
	//DIGITAL
	int SIDECAR_SLOT = SensorBase.getDefaultDigitalModule();

	int WHEEL_ENCODER_SLOT = SIDECAR_SLOT;
	int WHEEL_ENCODER_RF_SOURCE_A = 1;
	int WHEEL_ENCODER_RF_SOURCE_B = 2;
	//FOR REAL ROBOT
//	int WHEEL_ENCODER_LF_SOURCE_A = 3;
//	int WHEEL_ENCODER_LF_SOURCE_B = 4;
//	int WHEEL_ENCODER_LR_SOURCE_A = 5;	
//	int WHEEL_ENCODER_LR_SOURCE_B = 6;	
	
	//INVERTED
	int WHEEL_ENCODER_LF_SOURCE_A = 4;
	int WHEEL_ENCODER_LF_SOURCE_B = 3;
	int WHEEL_ENCODER_LR_SOURCE_A = 6;	
	int WHEEL_ENCODER_LR_SOURCE_B = 5;	
	
	int WHEEL_ENCODER_RR_SOURCE_A = 7;
	int WHEEL_ENCODER_RR_SOURCE_B = 8;

	int CALIBRATION_ENCODER_SLOT = SIDECAR_SLOT;
	int CALIBRATION_ENCODER_SOURCE_A = 1;
	int CALIBRATION_ENCODER_SOURCE_B = 2;
	
	int TURRET_PAN_ENCODER_SOURCE_A = 11;
	int TURRET_PAN_ENCODER_SOURCE_B = 12;
	
	int LAUNCHER_ENCODER_MODULE = SIDECAR_SLOT;
	int LAUNCHER_TOP_ENCODER_A = 9;
	int LAUNCHER_TOP_ENCODER_B = 13;
	int LAUNCHER_ENCODER_BOTTOM_A = 10;
	int LAUNCHER_ENCODER_BOTTOM_B = 14;
	
	int TIPPER_MOTOR_SLOT = SIDECAR_SLOT;
	int TIPPER_MOTOR_CHANNEL = 5;
	
	int LOADER_MOTOR_SLOT = SIDECAR_SLOT;
	int LOADER_MOTOR_LEFT = 2;
	int LOADER_MOTOR_RIGHT = 1;
	int LOADER_MOTOR_CENTER = 3;
	int LOADER_MOTOR_TOP = 4;
	int VICTOR_TEST = LOADER_MOTOR_TOP;

	
	int LIMIT_SWITCH_SLOT = SIDECAR_SLOT;
	int LEFT_LIMIT_SWITCH_PORT = 1;
	int RIGHT_LIMIT_SWITCH_PORT = 2;
	int CENTER_LIMIT_SWITCH_PORT = 3;
	int TOP_LIMIT_SWITCH_PORT = 4;
	
	
	int TIPPER_UP_LIMIT_SWITCH_PORT = 9;
	int TIPPER_DOWN_LIMIT_SWITCH_PORT = 6;
	
	int AUTONOMOUS_SWITCH_SLOT = SIDECAR_SLOT;
	int AUTONOMOUS_SWITCH_CHANNEL = 14;
	
	//PWM
	int MEC_SLOT = SIDECAR_SLOT;
	//REAL MOTOR VALUES!!
	int MEC_RF = 6;
	int MEC_LF = 7;
	int MEC_LB = 8;
	int MEC_RB = 9;
	
	//TEST MOTOR VALUES
//	/**
//	 * This is a test motor value and WILL NOT work on actual robot
//	 */
//	int MEC_RF = 1;
//	int MEC_LF = 2;
//	int MEC_LB = 3;
//	int MEC_RB = 4;
	////////////////
	
	//DRIVER STATION
	int PILOT_LEFT_JS = 1;
	int PILOT_RIGHT_JS = 2;
	int COPILOT_JS = 3;
	
	int PILOT_PAD = 1;
	int COPILOT_PAD = 2;

	//ANALOG
	int GYRO_BLUE = 1;
	int GYRO_RED = 2;
	int GYRO_PORT = GYRO_BLUE;
	
	//CAN
	int SHOOTER_TOP_CAN = 15;
	int SHOOTER_BOTTOM_CAN = 16;
//	int SHOOTER_TOP_CAN = 11;
//	int SHOOTER_BOTTOM_CAN = 12;
	int TURRET_CAN = 17;
	int WHEEL_RF_CAN = 11;
	int WHEEL_LF_CAN = 12;
	int WHEEL_LB_CAN = 13;
	int WHEEL_RB_CAN = 14;

	
	//TESTING
	int LOOKUP_TABLE_CONVEYOR_SLOT = SIDECAR_SLOT;
	int LOOKUP_TABLE_CONVEYOR_CHANNEL = 1;
	int CAN_TEST = SHOOTER_BOTTOM_CAN;

	int DEMO_SLOT = SIDECAR_SLOT;
	int DEMO_SHOOTER_CHANNEL = 1;
	int DEMO_TURRET_CHANNEL = 2;

	int SOLENIOD_RUNNER = 1;
	int THROUGH_BEAM_SENSOR = 2;
}
